
services:
  # 1. Serviço do Banco de Dados Relacional
  postgres:
    image: postgres:latest
    container_name: pg_integrated
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432" # 👈 Mantemos a porta externa 5433 para não bater com seu Postgres do Windows

  # 2. Serviço de Cache em Memória
  redis:
    image: redis:latest
    container_name: redis_integrated
    ports:
      - "6379:6379"

  # 3. Serviço de Mensageria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_integrated
    ports:
      - "5672:5672"
      - "15672:15672"
