# =========================================================================
# 📡 MANIFESTO KUBERNETES: SERVICE DA API MAESTRO
# =========================================================================
# O Service funciona como o "porteiro" e balanceador de carga (Load Balancer) do cluster.
# Como os Pods nascem e morrem com IPs dinâmicos, o Service cria um IP fixo e estável
# para que o mundo externo consiga acessar a API sem interrupções.

apiVersion: v1
kind: Service
metadata:
  name: maestro-api-service      # O nome único do porteiro de rede no cluster
  namespace: default             # Deve morar no mesmo namespace dos Pods para encontrá-los
  labels:
    app: maestro-api             # Etiqueta organizacional de catálogo
spec:
  # 🔀 TIPO DE EXPOSIÇÃO (NodePort): Perfeito para clusters de desenvolvimento locais.
  # Ele abre uma porta alta real na máquina hospedeira do cluster, permitindo que o
  # seu navegador de internet do Windows consiga conversar com os Pods de fora do Kubernetes!
  type: NodePort

  # O seletor diz ao Service exatamente para onde ele deve direcionar o tráfego recebido
  selector:
    app: maestro-api             # Alvo: captura e distribui as chamadas para os Pods com essa etiqueta

  ports:
    - name: http-rest            # Identificador do canal da nossa API REST e GraphQL
      protocol: TCP              # Protocolo unificado de transmissão estável de pacotes
      
      # 🚪 PORTA DE ENTRADA DO SERVICE: A porta que os outros componentes internos usam para se falar
      port: 3000
      
      # 🎯 PORTA DO CONTÊINER: A porta real que a nossa Factory do Node.js está ouvindo dentro do Pod
      targetPort: 3000
      
      # 🌐 PORTA DO MUNDO EXTERNO (NodePort): A porta real que o Kubernetes vai abrir na sua máquina.
      # Definimos a porta estrita '30100' (o Kubernetes aceita entre 30000 e 32767). 
      # Você acessará a API digitando http://localhost:30100 no Windows!
      nodePort: 30100
