// 1. IMPORTS: Bring in the repository contract and User data structure.
import { type IUserRepository } from "../interfaces/IUserRepository.js";
import { type User } from "../models/User.js";
import pg from 'pg'; // Use the official 'pg' driver to connect to the relational database.


// 2. CLASS: 'implements IUserRepository' tells TypeScript that this class
// must implement the three methods required by the contract (findAll, findById, create).
export class UserRepository implements IUserRepository {
  private pool: pg.Pool;
  
  constructor() {
    // 🔌 INVERSION OF CONTROL (IoC): Initialize the connection pool using container credentials.
    // Use Docker's internal port 5432 or the host port 5433 configured for this environment.
    this.pool = new pg.Pool({
      host: process.env.POSTGRES_HOST || 'localhost',
      user: process.env.POSTGRES_USER || 'postgres',
      password: process.env.POSTGRES_PASSWORD || 'secret',
      database: process.env.POSTGRES_DB || 'postgres',
      port: Number(process.env.POSTGRES_PORT) || 5433,
      max: 10, // Maximum concurrent pool connections to prevent memory leaks
      idleTimeoutMillis: 30000 // Close idle connections after 30 seconds to conserve resources
    });

    this.initDatabase();
  }

  /**
  * 🏗️ INFRASTRUCTURE INITIALIZATION (DDL):
  * Automatically create the users table at server startup if it does not exist.
   */
  private async initDatabase(): Promise<void> {
    const createTableQuery = `
      CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(50) PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `;
    try {
      await this.pool.query(createTableQuery);
      console.log('✅ [PostgreSQL] Tabela "users" validada e ativa no banco de dados.');
    } catch (error) {
      console.error('❌ Erro crítico ao tentar inicializar a tabela no PostgreSQL:', error);
    }
  }
              
  // // FUNCTION 1 (paginated findAll): Select a logical slice using the supplied numeric coordinates.
  // async findAll(limit: number, offset: number): Promise<User[]> {
  //   // .slice(offset, offset + limit) extracts the exact requested range.
  //   // Example: offset = 10, limit = 10 selects entries from position 10 through 20.
  //   return this.users.slice(offset, offset + limit);
  // }

  /**
  * 🔍 PAGINATED LIST FUNCTION (findAll):
  * Limit the number of returned records and skip earlier records in the SQL query.
   */
  async findAll(limit: number, offset: number): Promise<User[]> {
    const selectQuery = 'SELECT id, name, email FROM users ORDER BY created_at DESC LIMIT \$1 OFFSET \$2;';
    try {
      const result = await this.pool.query(selectQuery, [limit, offset]);
      return result.rows; // Return the rows retrieved from the relational database.
    } catch (error) {
      console.error('❌ Erro ao executar query findAll no PostgreSQL:', error);
      return [];
    }
  }

  // // FUNCTION 2: Accept an ID and use JavaScript's '.find()' method to search the array.
  // // Return the user if found, or null otherwise.
  // async findById(id: string): Promise<User | null> {
  //   return this.users.find((u) => u.id === id) || null;
  // }

  /**
  * 🎯 FIND BY ID FUNCTION (findById):
  * Safely locate a record using an indexed parameter.
   */
  async findById(id: string): Promise<User | null> {
    const selectByIdQuery = 'SELECT id, name, email FROM users WHERE id = \$1;';
    try {
      const result = await this.pool.query(selectByIdQuery, [id]);
      return result.rows[0] || null; // Return the matching user, or null if none exists.
    } catch (error) {
      console.error(`❌ Erro ao buscar usuário pelo ID ${id} no PostgreSQL:`, error);
      return null;
    }
  }

  // // FUNCTION 3: Accept a new user, add it to the array with '.push()',
  // // and return it to confirm that it was saved successfully.
  // async create(user: User): Promise<User> {
  //   this.users.push(user);
  //   return user;
  // } 
  
  /**
  * 📥 WRITE FUNCTION (create):
  * Insert the data generated by the service into the corresponding PostgreSQL columns.
   */
  async create(user: User): Promise<User> {
    const insertQuery = 'INSERT INTO users (id, name, email) VALUES (\$1, \$2, \$3) RETURNING id, name, email;';
    try {
      const result = await this.pool.query(insertQuery, [user.id, user.name, user.email]);
      return result.rows[0];
    } catch (error) {
      console.error('❌ Falha operacional ao tentar persistir usuário no PostgreSQL:', error);
      throw new Error('Erro interno de gravação na camada de persistência relacional.');
    }
  }
}


